-- ============================================================
-- 🚨 1. 毁灭阶段 (清理旧数据和冲突)
-- ============================================================
-- 删除冲突的函数 (解决 "cannot change name of input parameter" 报错)
DROP FUNCTION IF EXISTS get_trip_owner(bigint) CASCADE;

-- 删除所有相关表 (解决表结构不一致、缺列、依赖死锁等问题)
-- 注意：CASCADE 会自动清理关联的 RLS 策略，不用手动删策略
DROP TABLE IF EXISTS public.memories CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.likes CASCADE;
DROP TABLE IF EXISTS public.trip_members CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.days CASCADE;
DROP TABLE IF EXISTS public.trips CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================================
-- 🏗️ 2. 重建阶段 (创建完美结构的表)
-- ============================================================
create extension if not exists "uuid-ossp";

-- [表 1] 用户档案表 (Profiles) - 必须最先创建，以便其他表引用
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text unique,
  avatar_url text,
  notification_settings jsonb default '{"email_updates": true, "push_invites": true, "push_comments": true}'::jsonb,
  updated_at timestamp with time zone
);

-- 函数：新建用户时自动创建 Profile
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- 触发器：注册后触发
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 函数：更新用户时同步 Profile
create or replace function public.handle_user_update() 
returns trigger as $$
begin
  update public.profiles
  set full_name = new.raw_user_meta_data->>'full_name',
      avatar_url = new.raw_user_meta_data->>'avatar_url',
      email = new.email,
      updated_at = now()
  where id = new.id;
  return new;
end;
$$ language plpgsql security definer;

-- 触发器：更新后触发
create or replace trigger on_auth_user_updated
  after update on auth.users
  for each row execute procedure public.handle_user_update();

-- 🛠️ 补救措施：同步现有用户到 Profiles (防止重置数据库后老用户无法创建行程)
insert into public.profiles (id, email, full_name, avatar_url)
select 
  id, 
  email, 
  raw_user_meta_data->>'full_name', 
  raw_user_meta_data->>'avatar_url'
from auth.users
on conflict (id) do nothing;


-- [表 2] 行程表 (Trips)
create table public.trips (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_date date,
  cover_image text,
  is_public boolean default false,
  user_id uuid references public.profiles(id) on delete cascade, -- 关联到 profiles
  budget numeric default 0,
  description text
);

-- [表 3] 天数表 (Days)
create table public.days (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  day_index int not null,
  date date,
  title text
);

-- [表 4] 活动表 (Activities)
create table public.activities (
  id bigint generated by default as identity primary key,
  day_id bigint references public.days(id) on delete cascade not null,
  type text default 'spot',
  title text not null,
  location text,
  lat double precision,
  lng double precision,
  time time,
  memo text,
  sort_order int default 0,
  transport_mode text,
  is_tentative boolean default false,
  images text[] default '{}',
  cost numeric default 0,
  transport_time text,
  transport_distance text,
  transport_cost numeric default 0,
  link text
);

-- [表 5] 成员协作表 (Trip Members)
create table public.trip_members (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null, -- 关联到 profiles
  role text check (role in ('viewer', 'editor', 'owner')) default 'viewer',
  email text, -- 可选 (允许为空)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(trip_id, user_id) -- 唯一约束
);

-- ============================================================
-- 📦 3. 存储桶配置
-- ============================================================
insert into storage.buckets (id, name, public) 
values ('trip_images', 'trip_images', true)
on conflict (id) do nothing;

drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Public Upload" on storage.objects;

create policy "Public Access" on storage.objects for select using ( bucket_id = 'trip_images' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'trip_images' );

-- [表 5] 灵感回忆表 (Memories)
create table public.memories (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null, -- 关联到 profiles
  content text,
  images text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [表 6] 评论表 (Comments)
create table public.comments (
  id bigint generated by default as identity primary key,
  memory_id bigint references public.memories(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null, -- 关联到 profiles
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [表 7] 点赞表 (Likes)
create table public.likes (
  id bigint generated by default as identity primary key,
  memory_id bigint references public.memories(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null, -- 关联到 profiles
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(memory_id, user_id)
);

-- ============================================================
-- ⚡ 4. 实时同步 (Realtime)
-- ============================================================
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table public.trips, public.days, public.activities, public.trip_members, public.memories, public.comments, public.likes;
commit;

-- ============================================================
-- 🛡️ 5. 安全策略 (RLS)
-- ============================================================
alter table public.trips enable row level security;
alter table public.days enable row level security;
alter table public.activities enable row level security;
alter table public.trip_members enable row level security;
alter table public.profiles enable row level security;
alter table public.memories enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;

-- ... (Existing Profile Policies) ...

-- (E) Memories, Comments, Likes 策略
-- 只要能看行程(trip)，就能看相关的内容
create policy "Memories viewable" on memories for select using (
  exists (select 1 from trips where id = memories.trip_id and (is_public = true or user_id = auth.uid()))
  or exists (select 1 from trip_members where trip_id = memories.trip_id and user_id = auth.uid())
);
create policy "Comments viewable" on comments for select using (
  exists (select 1 from memories m join trips t on m.trip_id = t.id where m.id = comments.memory_id and (t.is_public = true or t.user_id = auth.uid()))
  or exists (select 1 from memories m join trip_members tm on m.trip_id = tm.trip_id where m.id = comments.memory_id and tm.user_id = auth.uid())
);
create policy "Likes viewable" on likes for select using (
  exists (select 1 from memories m join trips t on m.trip_id = t.id where m.id = likes.memory_id and (t.is_public = true or t.user_id = auth.uid()))
  or exists (select 1 from memories m join trip_members tm on m.trip_id = tm.trip_id where m.id = likes.memory_id and tm.user_id = auth.uid())
);

-- 只有参与者(Member)或Owner可以发布/评论/点赞
create policy "Memories insertable" on memories for insert with check (
  exists (select 1 from trips where id = trip_id and user_id = auth.uid())
  or exists (select 1 from trip_members where trip_id = memories.trip_id and user_id = auth.uid())
);
create policy "Comments insertable" on comments for insert with check (
  exists (select 1 from memories m join trips t on m.trip_id = t.id where m.id = memory_id and t.user_id = auth.uid())
  or exists (select 1 from memories m join trip_members tm on m.trip_id = tm.trip_id where m.id = memory_id and tm.user_id = auth.uid())
);
create policy "Likes insertable" on likes for insert with check (
  exists (select 1 from memories m join trips t on m.trip_id = t.id where m.id = memory_id and t.user_id = auth.uid())
  or exists (select 1 from memories m join trip_members tm on m.trip_id = tm.trip_id where m.id = memory_id and tm.user_id = auth.uid())
);
-- 删除自己的
create policy "Memories deletable" on memories for delete using (user_id = auth.uid());
create policy "Comments deletable" on comments for delete using (user_id = auth.uid());
create policy "Likes deletable" on likes for delete using (user_id = auth.uid());

-- Profiles 策略
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- (D) 用户自毁账户功能
create or replace function delete_own_account()
returns void
language plpgsql
security definer
as $$
begin
  -- 删除 auth.users 会自动级联删除 profiles 等所有关联数据(如果外键设置正确)
  delete from auth.users where id = auth.uid();
end;
$$;

-- 【关键函数】
create function get_trip_owner(target_trip_id bigint)
returns uuid
language sql
security definer
set search_path = public
as $$
  select user_id from trips where id = target_trip_id;
$$;

-- (A) Trips 策略
create policy "Trips viewable" on trips for select using (
  is_public = true 
  or auth.uid() = user_id 
  or exists (select 1 from trip_members where trip_id = trips.id and user_id = auth.uid())
);
create policy "Trips owner manage" on trips for all using (
  auth.uid() = user_id
);

-- (B) Trip Members 策略
create policy "Members view" on trip_members for select using (
  user_id = auth.uid() 
  or auth.uid() = get_trip_owner(trip_id)
);
create policy "Members leave" on trip_members for delete using (
  user_id = auth.uid()
);
create policy "Owner manage members" on trip_members for insert with check (
  auth.uid() = get_trip_owner(trip_id)
);
create policy "Owner delete members" on trip_members for delete using (
  auth.uid() = get_trip_owner(trip_id)
);

-- (C) Days & Activities 策略
-- 查看
create policy "Content viewable" on days for select using (
  exists (select 1 from trips where id = days.trip_id and (is_public = true or user_id = auth.uid()))
  or exists (select 1 from trip_members where trip_id = days.trip_id and user_id = auth.uid())
);
create policy "Content viewable" on activities for select using (
  exists (
    select 1 from days join trips on days.trip_id = trips.id 
    where days.id = activities.day_id 
    and (trips.is_public = true or trips.user_id = auth.uid())
  )
  or exists (
    select 1 from days join trip_members on days.trip_id = trip_members.trip_id
    where days.id = activities.day_id and trip_members.user_id = auth.uid()
  )
);
-- 编辑
create policy "Content editable" on days for all using (
  exists (select 1 from trips where id = days.trip_id and user_id = auth.uid())
  or exists (select 1 from trip_members where trip_id = days.trip_id and user_id = auth.uid() and role in ('editor', 'owner'))
);
create policy "Content editable" on activities for all using (
  exists (
    select 1 from days join trips on days.trip_id = trips.id 
    where days.id = activities.day_id and trips.user_id = auth.uid()
  )
  or exists (
    select 1 from days join trip_members on days.trip_id = trip_members.trip_id
    where days.id = activities.day_id and trip_members.user_id = auth.uid() and role in ('editor', 'owner')
  )
);
